Update to more closely follow Plushu style guide

diff --git a/pluchu b/pluchu
--- a/pluchu
+++ b/pluchu
@@ -7,10 +7,10 @@
 
 # The name of the user / remote.
 # Changing this to "dokku" will make a client script for dokku.
-SERVNAME="plushu"
+servname="plushu"
 
 # Set the "REMOTE" variable according to any "remote" command-line arg.
-case $1 in
+case "$1" in
   --remote)
     shift
     REMOTE=$1
@@ -22,21 +22,22 @@ case $1 in
 esac
 
 # The name of the Git remote to read the server URL from.
-# By default, the remote name is $SERVNAME ("plushu"):
+# By default, the remote name is $servname ("plushu"):
 # you can change that here.
-REMOTE=${REMOTE:-$SERVNAME}
-REMOTE_URL=$(git config --get remote.$REMOTE.url)
+REMOTE=${REMOTE:-$servname}
+remote_url=$(git config --get remote.$REMOTE.url)
 
-if [ $? -ne 0 ]; then
-    echo "Remote \"$REMOTE\" not found"
-    exit 1
+if [[ "$?" -ne 0 ]]; then
+  echo "Remote \"$REMOTE\" not found"
+  exit 1
 fi
 
 # Safety check that the remote user name is the same as the expected service
-if [ ${REMOTE_URL%%@*} != $SERVNAME ]; then
-    echo "Remote \"$REMOTE\" does not appear to be a $SERVNAME server"
-    exit 1
+if [[ "${remote_url%%@*}" != "$servname" ]]; then
+  echo "Remote \"$REMOTE\" does not appear to be a $servname server"
+  exit 1
 fi
 
-REMOTE_HOST=${REMOTE_URL%%:*}
-ssh "$REMOTE_HOST" "$@"
+host=${remote_url%%:*}
+
+ssh "$host" "$@"
